//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using AssemblyCSharp;
using UnityEngine;

namespace AssemblyCSharp
{
	public class Level
	{
		
		public int sizeX, sizeY;
		public Block[,] world;
		public Point enter;
		public Point exit;
		
		public class Block
		{
			public bool isEdgeWorldTop = false;
			public bool isEdgeWorldBottom = false;
			public bool isEdgeWorldLeft = false;
			public bool isEdgeWorldRight = false;
			public bool isWallTop = false;
			public bool isWallBottom = false;
			public bool isWallLeft = false;
			public bool isWallRight = false;
			public bool isWall = true;
			public int type;
			
			public Block()
			{
				type = 0;
			}
		}
		
		public Level()
		{
			sizeX = 100;
			sizeY = 100;
			world = new Block[sizeX, sizeY];
			
			for (int x = 0; x < sizeX; x++)
			{
				for (int y = 0; y < sizeY; y++)
				{
					world[x, y] = new Block();
					world[x, y].type = UnityEngine.Random.Range(0, 2);
				}
			}
		}
		
		public Level(int sizeX, int sizeY)
		{
			this.sizeX = sizeX;
			this.sizeY = sizeY;
			world = new Block[sizeX, sizeY];
			
			for (int x = 0; x < sizeX; x++)
			{
				for (int y = 0; y < sizeY; y++)
				{
					world[x, y].type = UnityEngine.Random.Range(0, 2);
				}
			}
		}
	}
}

